name: Run Custom Action

on:
    workflow_dispatch:

jobs:
    run-action:
        runs-on: ubuntu-latest
        steps:
            - uses: tjamet/composite-action-test-2@main
            - uses: tjamet/composite-action-test@v1
